FROM ubuntu:20.04
RUN sed -i 's/http:\/\/archive.ubuntu.com/http:\/\/archive.ubuntu.com\/ubuntu/' /etc/apt/sources.list

RUN DEBIAN_FRONTEND=noninteractive apt update -y --fix-missing && apt upgrade -y

RUN DEBIAN_FRONTEND=noninteractive apt install -y build-essential git graphviz g++ libhttp-parser-dev libbsd-dev pkg-config libssl-dev cmake

WORKDIR /tmp
RUN git clone https://github.com/NTAP/quant.git quant
WORKDIR /tmp/quant
RUN git checkout 511d91c3
RUN git submodule update --init --recursive
RUN mkdir Release

WORKDIR /tmp/quant/Release
RUN cmake -DCMAKE_BUILD_TYPE=Release ..
RUN make

RUN DEBIAN_FRONTEND=noninteractive apt install -y pip python3-tk lsof libssl-dev python3-dev default-jdk

RUN pip install asgiref dnslib httpbin starlette wsproto aioquic pydot && \
    pip install asgiref dnslib httpbin starlette wsproto --no-cache-dir && \
    pip install Werkzeug==2.0.3 && \
    pip install "flask<2.2.0"

WORKDIR /tmp/quicLearner
RUN python3 -m pip install pydot py4j==0.10.9.7

COPY run_fuzzing.sh /run_fuzzing.sh
RUN chmod +x /run_fuzzing.sh

ENTRYPOINT ["/run_fuzzing.sh"]