title : AALpy
author: Edi Muskardin
description: An Active Automata Learning Library
rss-description: An Active Automata Learning Library
theme: jekyll-theme-slate
google-site-verification: google306875680a34d740.html