#!/bin/bash

ulimit -s 16384

setsid python3 learner.py -s $SERVER_NAME --config $CONFIG -i $INPUT_TEMP -p $LEARNER_PORT_TEMP -t $SERVER_PORT_TEMP -c $CLIENT_CERT -k $CLIENT_KEY $LEARN_LIB --docker -r "$SERVER_PATH ./ -c $SERVER_CERT -k $SERVER_KEY --listen 127.0.0.1:$SERVER_PORT_TEMP $RETRY $CLIENT_AUTH $CA_CERT" > run/learner_${SERVER_NAME}_${INPUT_TEMP}_${LEARNER_PORT_TEMP}.log 2>&1 &
setsid python3 learner.py -s $SERVER_NAME --config $CONFIG -i $INPUT_SHORT -p $LEARNER_PORT_SHORT -t $SERVER_PORT_SHORT -c $CLIENT_CERT -k $CLIENT_KEY $LEARN_LIB --docker -r "$SERVER_PATH ./ -c $SERVER_CERT -k $SERVER_KEY --listen 127.0.0.1:$SERVER_PORT_SHORT $RETRY $CLIENT_AUTH $CA_CERT" > run/learner_${SERVER_NAME}_${INPUT_SHORT}_${LEARNER_PORT_SHORT}.log 2>&1 & 
setsid python3 learner.py -s $SERVER_NAME --config $CONFIG -i $INPUT_LONG -p $LEARNER_PORT_LONG -t $SERVER_PORT_LONG -c $CLIENT_CERT -k $CLIENT_KEY $LEARN_LIB --docker -r "$SERVER_PATH ./ -c $SERVER_CERT -k $SERVER_KEY --listen 127.0.0.1:$SERVER_PORT_LONG $RETRY $CLIENT_AUTH $CA_CERT" > run/learner_${SERVER_NAME}_${INPUT_LONG}_${LEARNER_PORT_LONG}.log 2>&1 &

wait